const stepData=[
  {title:'Знакомство с игрой',text:'Новичкам объясняют правила перед игрой. Дилер ведёт раздачу и помогает с порядком действий за столом.',image:'image-8.webp',alt:'Игроки за столом'},
  {title:'За игровым столом',text:'В клубе играют в техасский холдем на турнирные фишки. Денежных ставок за столом нет.',image:'image-3.webp',alt:'Игроки и команда у покерного стола'},
  {title:'Перерыв и общение',text:'Между раздачами гости общаются, встречаются у бара и возвращаются к игре.',image:'image-2.webp',alt:'Гости общаются во время вечера'},
  {title:'Финал вечера',text:'Партия заканчивается, а знакомства и впечатления от вечера остаются.',image:'image-9.webp',alt:'Участники вечера с кубком'}
];
document.querySelectorAll('.step').forEach(button=>button.addEventListener('click',()=>{const index=Number(button.dataset.step),data=stepData[index];document.querySelectorAll('.step').forEach(item=>{item.classList.toggle('active',item===button);item.setAttribute('aria-selected',item===button?'true':'false')});document.querySelector('#step-number').textContent=`ЭТАП 0${index+1}`;document.querySelector('#step-title').textContent=data.title;document.querySelector('#step-description').textContent=data.text;const image=document.querySelector('#step-photo');image.src=`assets/${data.image}`;image.alt=data.alt}));
const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('.site-head nav');menu.addEventListener('click',()=>{const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Закрыть меню':'Открыть меню');menu.textContent=open?'×':'☰'});nav.querySelectorAll('a').forEach(link=>link.addEventListener('click',()=>{nav.classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Открыть меню');menu.textContent='☰'}));
const dialog=document.querySelector('#lightbox');document.querySelectorAll('[data-photo]').forEach(button=>button.addEventListener('click',()=>{dialog.querySelector('img').src=`assets/${button.dataset.photo}`;dialog.showModal()}));dialog.querySelector('.close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close()});
