const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const url=id=>'case.html?project='+encodeURIComponent(id);
async function boot(){const response=await fetch('data.json');if(!response.ok)throw Error('data');const data=await response.json();
if($('#case-main')){await showCase(data);return}let selected='Все',limit=12;
function hero(id){const p=data.find(x=>x.id===id);$('#hero-image').src=p.desktop;$('#hero-image').alt=p.subtitle;$('#hero-title').textContent=p.name;$('#hero-project').href=$('#hero-link').href=url(id);$('#hero-project').setAttribute('aria-label','Открыть кейс '+p.name);document.querySelectorAll('[data-hero]').forEach((b,i)=>{const on=b.dataset.hero===id;b.setAttribute('aria-pressed',on);if(on)$('#hero-number').textContent='0'+(i+1)+' / 03'})}hero('ritm');document.querySelectorAll('[data-hero]').forEach(b=>b.addEventListener('click',()=>hero(b.dataset.hero)));
$('#featured').innerHTML=['ritm','pifpaf','ep-beauty','garmony','support-rag'].map(id=>{const p=data.find(x=>x.id===id);return `<article class="feature"><a class="feature-media" href="${url(id)}" aria-label="Открыть кейс ${esc(p.name)}"><img src="${esc(p.desktop)}" alt="${esc(p.subtitle)}" width="1440" height="900" loading="lazy"></a><div class="feature-copy"><span class="category">${esc(p.category)}</span><h3><a href="${url(id)}">${esc(p.name)}</a></h3><p>${esc(p.intro)}</p><a class="arrow" href="${url(id)}" aria-label="Подробнее о ${esc(p.name)}">↗</a></div></article>`}).join('');
const more=document.createElement('button');more.className='text-link more';more.textContent='Показать остальные работы ↓';$('#catalog').after(more);more.addEventListener('click',()=>{limit=Infinity;render()});
function render(){const q=$('#search').value.toLocaleLowerCase('ru').trim(),rows=data.filter(p=>(selected==='Все'||p.category===selected)&&[p.name,p.subtitle,p.intro].join(' ').toLocaleLowerCase('ru').includes(q)),shown=rows.slice(0,limit);$('#catalog').innerHTML=shown.map(p=>`<a class="catalog-item" href="${url(p.id)}"><img src="${esc(p.desktop)}" loading="lazy" width="75" height="54" alt=""><h3>${esc(p.name)}</h3><p>${esc(p.subtitle)}</p><small>${esc(p.category)}</small><span aria-hidden="true">↗</span></a>`).join('');$('#result-count').textContent=`${shown.length} из ${rows.length}`;$('#empty').hidden=rows.length>0;more.hidden=shown.length===rows.length}
$('#search').addEventListener('input',()=>{limit=Infinity;render()});document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>{selected=b.dataset.filter;limit=Infinity;document.querySelectorAll('[data-filter]').forEach(x=>x.setAttribute('aria-pressed',x===b));render()}));render();$('#copy-contact').addEventListener('click',async()=>{try{await navigator.clipboard.writeText('@solonflowai');$('#copy-status').textContent='Контакт скопирован: @solonflowai'}catch{$('#copy-status').textContent='Контакт: @solonflowai — можно скопировать вручную.'}});
}
function markdown(raw){return raw.split(/\n\s*\n/).map(b=>{const h=b.match(/^#{1,3}\s+(.+)$/);if(h)return '<h3>'+esc(h[1])+'</h3>';return '<p>'+esc(b).replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\n/g,'<br>')+'</p>'}).join('')}
async function showCase(data){const id=new URLSearchParams(location.search).get('project'),p=data.find(x=>x.id===id),root=$('#case-main');if(!p){document.title='Проект не найден';root.innerHTML='<h1>Проект не найден.</h1><p>Возможно, ссылка изменилась.</p><a class="text-link" href="./#archive">Открыть каталог ↗</a>';return}document.title=p.name+' — Никита Солонуха';const next=data[(data.indexOf(p)+1)%data.length];
const media=p.media.map((v,i)=>`<figure><div class="${v.mobile?'device-phone':'device-laptop'}"><video controls playsinline preload="metadata" poster="${esc(v.poster)}" aria-label="${esc(p.name)} — ${v.mobile?'мобильная':'десктопная'} демонстрация ${i+1}"><source src="${esc(v.src)}" type="video/mp4"></video></div><figcaption>${v.mobile?'iPhone · мобильный сценарий':'MacBook · десктопный сценарий'}${i>1?' / дополнительная запись':''}</figcaption></figure>`);let pairs='';for(let i=0;i<media.length;i+=2)pairs+='<div class="media-pair">'+media.slice(i,i+2).join('')+'</div>';
root.innerHTML=`<a class="text-link" href="./#archive">← Все работы</a><div class="case-intro"><div><p class="eyebrow">${esc(p.category)} / выбранная работа</p><h1>${esc(p.name)}</h1><p class="subtitle">${esc(p.subtitle)}</p></div><p class="brief">${esc(p.intro)}</p></div><div class="case-overview"><img src="${esc(p.desktop)}" alt="${esc(p.subtitle)}" width="1440" height="900"></div><div class="case-facts"><div><h2>Внутри проекта</h2><p>${esc(p.flow)}</p><p class="stack">${esc(p.stack)}</p></div><div class="case-boundary"><p class="eyebrow">Что показано в кейсе</p><p>${esc(p.boundary)}</p><a class="text-link" href="#evidence">Факты и источники ↓</a></div></div><section class="walkthrough"><p class="eyebrow">Посмотреть в действии</p><h2>От действия —<br><em>к результату.</em></h2>${pairs}</section>${p.screens.length?`<section class="case-screens"><h2>Ближе к деталям.</h2><div class="screen-grid">${p.screens.map((s,i)=>`<img src="${esc(s)}" alt="${esc(p.name)} — дополнительный экран ${i+1}" loading="lazy">`).join('')}</div></section>`:''}<details class="evidence" id="evidence"><summary>Исследование и границы проверки</summary><div class="evidence-content">Загрузка описания…</div></details><p class="local-note">Локальная версия портфолио. Разрешение на публичный показ, личный вклад и внешние интеграции отмечены в исследовании; наличие демо не подтверждает работу production.</p><a class="text-link" href="${esc(p.research)}">Все материалы проекта ↗</a><nav class="case-next" aria-label="Другие проекты"><a href="./#archive">← Вернуться к работам</a><a href="${url(next.id)}">${esc(next.name)} →</a></nav>`;
document.querySelectorAll('video').forEach(v=>v.addEventListener('play',()=>document.querySelectorAll('video').forEach(other=>{if(other!==v)other.pause()})));try{const res=await fetch(p.document);if(!res.ok)throw Error('document');$('.evidence-content').innerHTML=markdown(await res.text())}catch{$('.evidence-content').innerHTML=`<a href="${esc(p.document)}">Открыть файл исследования ↗</a>`}
}
boot().catch(()=>{const root=$('#catalog')||$('#case-main');if(root)root.innerHTML='<p>Не удалось загрузить проекты. <a href="../review/index.html">Открыть галерею материалов ↗</a></p>'});
